import React,{useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import pink from './assets/pink-butterfly.jpg';
import bee from './assets/bee-pillow.jpg';
import blue from './assets/blue-pillow.jpg';

const products=[
 {name:'Butterfly Cloud',price:'₹1,299',img:pink,tag:'BEST SELLER'},
 {name:'Busy Bee',price:'₹1,299',img:bee,tag:'CUTE PICK'},
 {name:'Blue Orbit',price:'₹1,399',img:blue,tag:'NEW'}
];
function TiltCard({children,className=''}){const ref=useRef(null);const move=e=>{const r=ref.current.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;ref.current.style.setProperty('--rx',`${-y*8}deg`);ref.current.style.setProperty('--ry',`${x*10}deg`)};const leave=()=>{ref.current.style.setProperty('--rx','0deg');ref.current.style.setProperty('--ry','0deg')};return <div ref={ref} onMouseMove={move} onMouseLeave={leave} className={'tilt '+className}>{children}</div>}
function App(){const [cart,setCart]=useState(0);const [menu,setMenu]=useState(false);const add=()=>setCart(c=>c+1);return <div className="site">
<header><div className="brand"><span className="brand-bunny">🐰</span><div><strong>Little <i>Orbit</i></strong><small>Care • Comfort • Safety</small></div></div><button className="hamb" onClick={()=>setMenu(!menu)}>☰</button><nav className={menu?'open':''}><a href="#home">Home</a><a href="#shop">Shop</a><a href="#features">Features</a><a href="#story">Our Story</a><a href="#reviews">Reviews</a></nav><div className="actions"><span className="search">⌕</span><span className="bag">🛍️<b>{cart}</b></span><button onClick={()=>document.querySelector('#shop').scrollIntoView({behavior:'smooth'})}>Order Now</button></div></header>
<main>
<section id="home" className="hero"><div className="cloud c1">☁️</div><div className="cloud c2">☁️</div><div className="star">★</div><div className="hero-copy"><span className="pill">⭐ Loved by little explorers</span><h1>Soft protection,<br/><em>big adventures.</em></h1><p>A cheerful safety pillow made for crawling, toddling and all those tiny everyday tumbles.</p><div className="hero-btns"><button className="primary" onClick={()=>document.querySelector('#shop').scrollIntoView({behavior:'smooth'})}>Shop the collection <span>→</span></button><button className="secondary">▶ Watch story</button></div><div className="trust"><span>✓ Baby-friendly materials</span><span>✓ Lightweight comfort</span></div></div><TiltCard className="hero-product"><div className="orbit-ring"></div><div className="float-heart">♥</div><img src={pink} alt="Pink butterfly baby safety pillow"/><div className="product-badge">360°<small>HEAD CARE</small></div></TiltCard><div className="bunny-scene">🐰</div><div className="flower">🌸</div></section>
<section className="marquee"><span>☁ Soft & cuddly</span><span>✦ Made for little movers</span><span>☀ Playful comfort</span><span>♡ Parent approved feel</span></section>
<section id="shop" className="shop"><div className="section-head"><div><span className="eyebrow">THE LITTLE COLLECTION</span><h2>Pick a <em>happy helper.</em></h2></div><p>Three playful looks, one cozy mission: make every little adventure feel more comfortable.</p></div><div className="products">{products.map((p,i)=><article className="product" key={p.name}><div className="product-image"><span className="tag">{p.tag}</span><img src={p.img} alt={p.name}/><span className="spark">✦</span></div><div className="product-info"><div><h3>{p.name}</h3><div className="stars">★★★★★ <small>({120+i*37})</small></div></div><strong>{p.price}</strong></div><button onClick={add}>Add to bag <span>+</span></button></article>)}</div></section>
<section id="features" className="features"><div className="feature-intro"><span className="eyebrow">WHY LITTLE ORBIT</span><h2>Comfort that<br/><em>moves with them.</em></h2><p>Designed around the way babies actually crawl, sit, wobble and explore.</p></div><div className="feature-grid"><div><span>☁</span><h3>Cloud Soft</h3><p>Gentle-feel cushioning for everyday comfort.</p></div><div><span>♡</span><h3>360° Care</h3><p>Wraparound shape adds cozy head-and-back support.</p></div><div><span>〰</span><h3>Airy Feel</h3><p>Lightweight construction made for movement.</p></div><div><span>✦</span><h3>Easy Adjust</h3><p>Straps designed to grow with little explorers.</p></div></div></section>
<section id="story" className="story"><div className="story-art"><div className="sun">☀</div><div className="hill"></div><div className="story-bunny">🐰</div><div className="cloud c3">☁️</div></div><div className="story-copy"><span className="eyebrow">OUR LITTLE STORY</span><h2>Built for the <em>first steps</em> of a big world.</h2><p>Little Orbit turns everyday safety into something babies love to wear. We pair playful characters with soft, practical design so protection never feels boring.</p><div className="stats"><div><b>01</b><span>Soft-first design</span></div><div><b>02</b><span>Playful characters</span></div><div><b>03</b><span>Parent peace of mind</span></div></div></div></section>
<section id="reviews" className="reviews"><span className="eyebrow">LITTLE LOVE NOTES</span><h2>“The cutest thing<br/><em>my little one wears.”</em></h2><div className="review-row"><span>★★★★★</span><p>“It looks like a tiny backpack, but my baby thinks it is a toy. The design is adorable.”</p><b>— Happy parent</b></div></section>
</main><footer><div className="brand"><span className="brand-bunny">🐰</span><div><strong>Little <i>Orbit</i></strong><small>Care • Comfort • Safety</small></div></div><p>Small explorers. Big little worlds. ✦</p><div>© 2026 Little Orbit</div></footer>
</div>}
createRoot(document.getElementById('root')).render(<App/>);
